services:
  noetic:
    build: .

    tty: true
    user: "1000"

    volumes:
      - type: bind
        source: $HOME/catkin_ws
        target: $CONTAINER_HOME/catkin_ws

      - type: bind
        source: $HOME/.ssh
        target: $CONTAINER_HOME/.ssh
